import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <head>
            <meta charSet="utf-8" />
            <title>Welcome to View Cart 24 </title>
            <meta name="title" content="Toilets, Showers, Sinks, Faucets, Bathroom & Kitchen Accessories - Kohler Nepal" />
            <meta name="keywords" content="Bathroom Accessories, Toilet Seats, Kohler Nepal" />
            <meta name="description" content="Kohler is a leading manufacturing brand in Nepal. We provide complete bathroom accessories, fittings, faucets, showers, toilet seats & bathtubs. Explore the exquisite" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="stylesheet" href="css/bootstrap.min.css" />
            <link rel="stylesheet" href="css/owl.theme.default.min.css" />
            <link rel="stylesheet" href="css/slick.css" />
            <link rel="stylesheet" href="css/slick-theme.css" />
            <link rel="stylesheet" href="css/icofont.min.css" />
            <link rel="stylesheet" href="css/magnific-popup.css" />
            <link rel="stylesheet" href="css/flaticon.css" />
            <link rel="stylesheet" href="css/meanmenu.css" />
            <link rel="stylesheet" href="css/style.css" />
            <link rel="stylesheet" href="css/responsive.css" />
            <link rel="stylesheet" href="css/jquery.fancybox.min.css" />
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
            <link rel="icon" type="image/png" href="images/favicon.png" /> 
            <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-countdown/2.0.2/jquery.countdown.css" rel="stylesheet" />
        </head>
      <body className={inter.className}>{children}</body>
        <Script src="/js/jquery-2.2.4.min.js"/>
        <Script src="/js/popper.min.js"/>
        <Script src="/js/bootstrap.min.js"/>
        <Script src="/js/slick.min.js"/>
        <Script src="/js/counter.min.js"/>
        <Script src="/js/waypoint.min.js"/>
        <Script src="/js/jquery.magnific-popup.min.js"/>
        <Script src="/js/meanmenu.js"/>
        <Script src="/js/jquery.ajaxchimp.min.js"/>
        <Script src="/js/form-validator.min.js"/>
        <Script src="/js/contact-form-Script.js"/>
        <Script src="/js/custom.js"/>
        <Script src="https://cdn.rawgit.com/hilios/jQuery.countdown/2.2.0/dist/jquery.countdown.min.js"/>
        <Script src="/js/theme.js"/>
        <Script src="/js/main.js"/>
        <Script src="/js/jquery.fancybox.min.js"/>
    </html>
    
  )
}
